name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Codigo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with: 
        mayor_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
        
    - name: docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Nueva version $NEW_VERSION!!!"
        
#     - name: Docker build image
#       run: |
#         docker build -t nestordaniel29/docker-graphql:0.0.2 .
#         docker build -t nestordaniel29/docker-graphql:latest .
        
#     - name: Push build image
#       run: |
#         docker push nestordaniel29/docker-graphql:0.0.2
#         docker push nestordaniel29/docker-graphql:latest
     
     
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

# token hub: dckr_pat_Ow3XS5WH2DxOjGJA9o_HKCHUw1o
